### ISSUE TITLE
input field does not work as expected

### ISSUE THREAD

**Issue by RoelofWobbenfrontend** [RoelofWobbenfrontend/tip-calculator-react#2]
I display now the text "Custom"  in the input field because the challenge asked me to do.
But as soon as I wants to enter something in it the text "Custom"  needs to be deleted.

I think I need to write a new state for the input field to make that work.
No idea how I can make it empty when I click on the input field.

**Comment by samjok** [comment]
This "Custom" text can be set as placeholder of input element.
https://www.w3schools.com/tags/att_input_placeholder.asp

**Comment by RoelofWobbenfrontend** [comment]
I know but I mean if you want to enter something in that field , the contents of the input field must be empty.
So the text "Custom"  needs to be deleted.

**Comment by samjok** [comment]
A placeholder attribute works that way. You can try it in the link above (there is "Try it yourself" button).

**Comment by RoelofWobbenfrontend** [comment]
Thanks, it seems to work.
The only thing I need to do is when you add a percentage to the input field its need to convert to a float, divide by 100 and be back to a string.  Because otherwise we get very strange outcomes when trying to calculate it.

**Comment by RoelofWobbenfrontend** [comment]
also solved now I think.
Can you check the "test-input" branch before im going to merge this.
Things are now simpler in react then in javascript. 
This part costed me I think 2 weeks ( 8 hours) to make this work in javascript and some 2 - 3 hours in react.

**Comment by samjok** [comment]
I think you still need to convert those strings (like "0.05") to numbers. You could do that in changePercentage function in App.js file:

```
  const changePercentage = (newPercentage) => {
    setTipPercentage(Number(newPercentage));
  };
```

**Comment by RoelofWobbenfrontend** [comment]
yep but then the className does not work. Value is always a string.

**Comment by samjok** [comment]
You can also give a value as number.
´´´
        <Button
          id="five"
          value={0.05}
          onClick={() => changeValue("0.05")}
          tipPercentage={tipPercentage}
        />
´´´
But you can also do it that way you said.

**Comment by RoelofWobbenfrontend** [comment]
Did not know that. but I like it better. 
When doing the calculations I do not have to convert everything.
Thanks for the hint.
