### ISSUE TITLE
How to add  a custom class "selected" to a button or the input field

### ISSUE THREAD

**Issue by RoelofWobbenfrontend** [RoelofWobbenfrontend/tip-calculator-react#3]
I need somehow to add   a selected class to the button clicked or to the input field so I can use some css to let the user see if he/she has selected a percentage or entered a custom percentage. 

I can use another state to keep track if for example selected is true when a button is chosen and false when the input field is chosen.
But then for so far I know I cannot use css to change the layout.

**Comment by samjok** [comment]
Here is one possible way to change className when user clicks a button:

`
import React, { useState } from "react";
import "./test.css";

const Test = () => {
  const [isButtonSelected, setIsButtonSelected] = useState(false);

  const buttonClassName = isButtonSelected ? "defaultButton" : "selectedButton";

  return (
    <button
      className={buttonClassName}
      onClick={() => setIsButtonSelected(!isButtonSelected)}
    >
      Click me
    </button>
  );
};

export default Test;
`

And in the css file need to be defined both classNames:

`
.defaultButton {
  background-color: green;
}

.selectedButton {
  background-color: red;
}
`

**Comment by RoelofWobbenfrontend** [comment]
I will try it this weeked on the code.
Curious what happens if you select one and after that select another.

I think we can use the same prop-drilling like we did with the value of the button.
Or am I mistaken?

**Comment by RoelofWobbenfrontend** [comment]
I looked again at the code and I think we do not need the code 
if I look at the className part here : 
```
const Button = ({ id, value, onClick, tipPercentage }) => {
  return (
    <>
     <button
        onClick={onClick}
        id={id}
        className={tipPercentage === value ? "selected" : "unselected"}
        value={value}>
          {value}
      </button>
    </>
  );
};

export default Button;
````
then the part is already done but on some way it does not work.
When you click on the button, the className is not changed.

Is there a way we can see the values of value and tipPercentage ?

**Comment by RoelofWobbenfrontend** [comment]
chips. I see the problem
When I use react-developer tools I see that tipPercentage is 0.05 but value is "0.05" 
and that gives false. 

I have to think good how to solve that.

**Comment by RoelofWobbenfrontend** [comment]
Solved by the "test-selected"  branch.

Is the solution good so we can make a PR of it ?

**Comment by samjok** [comment]
It seems your text input field doesn't yet work in such way you wanted. I think you need own state for text input value. It can't be fixed string because then it will never change.

**Comment by RoelofWobbenfrontend** [comment]
Why do you think it does not work.
When i now enter  6  in the input field , 0,.06 is stored in the tipPercentage field.
That is exactly what I want.

**Comment by samjok** [comment]
Oh, sorry, now I see it working.

**Comment by RoelofWobbenfrontend** [comment]
NP

**Comment by RoelofWobbenfrontend** [comment]
Merge the two branches and then try to make the amount input field work or can I better add already validation to the input field.

**Comment by samjok** [comment]
I would make all main functionalities first and add details (like validation) later. But do whatever you feel you want to do next.

**Comment by RoelofWobbenfrontend** [comment]
oke, then the next one would be to add all the buttons and add all the html code to add a amount.
So it looks more and more like the one I have made with javascript.

But first if you do not have any remarks merge the two branches.
And I see more and more why people use react instead of plain javascript to make this sort of things.
But glad im learning javascript first.

**Comment by samjok** [comment]
I think you can merge them now. But if you want to do this with best practices, create first pull request of your task branch to main branch. That way you can ask other people review your pull request.
