### ISSUE TITLE
How to display the calculations.

### ISSUE THREAD

**Issue by RoelofWobbenfrontend** [RoelofWobbenfrontend/tip-calculator-react#7]
I can make a component to calcualate the data we wanted but still I do not know how to display that data then ?

**Comment by samjok** [comment]
Data can be displayed in JSX using curly brackets.
```
<div>{data}<div>
```

**Comment by RoelofWobbenfrontend** [comment]
oke,

How do we get then the data we need (amount, persons, tip) to the component so things can be calculated.
The same way as we did with the input fields ?

**Comment by RoelofWobbenfrontend** [comment]
@samjok  ping.  I hope we can still work together. 
This one is almost done

**Comment by samjok** [comment]
Yes, we can work together. But I just did a positive Covid test and currently I can't think too much. Maybe in next weekend I can contribute more again. I'll check your code when I feel better.

**Comment by RoelofWobbenfrontend** [comment]
Oke, 

Wish that  you will be better soon and do not have to much health problems. 
it's oke to wait some time. Take your time to get better first

**Comment by RoelofWobbenfrontend** [comment]
@samjok  how are you doing ?

**Comment by samjok** [comment]
I'm fine. Is this issue still unsolved?

**Comment by RoelofWobbenfrontend** [comment]
yep. 

I still wonder if I can make the outcome displayed the same way as I did with the functions ?

**Comment by samjok** [comment]
There is now display component on data-display branch. And input for bill. Number of persons is still missing but it can be next task. Components still needs styling.

**Comment by RoelofWobbenfrontend** [comment]
yep I saw that the buttons displays the wrong value and the custom is on the wrong place.
I have to dive in why the custom is on the wrong place.
For the wrong display I have made a new issue

**Comment by RoelofWobbenfrontend** [comment]
Hello, 

I added the calculation part and it sends the right data to the outcome component but on some way I do not understand it will not rerender or display the right data.

@samjok  can  you take a look at this so this project is almost ending
